param(
    [string]$DatabaseHost = "127.0.0.1",
    [int]$Port = 3306,
    [string]$User = "root",
    [string]$Password = $env:DB_PASSWORD
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$configDirectory = Join-Path $root "config"
$configFile = Join-Path $configDirectory "application-local.properties"

function ConvertTo-PlainText([Security.SecureString]$SecureValue) {
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureValue)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
}

function ConvertTo-PropertyValue([AllowEmptyString()][string]$Value) {
    if ($Value -match "[\r\n]") {
        throw "Database configuration values must not contain line breaks."
    }
    return $Value.Replace("\", "\\").Replace(":", "\:").Replace("=", "\=").Replace("#", "\#").Replace("!", "\!")
}

if (-not (Get-Command mysql.exe -ErrorAction SilentlyContinue)) {
    throw "mysql.exe was not found. Install MySQL 8 and add its bin directory to PATH."
}

if (-not $Password) {
    $securePassword = Read-Host "Enter the local MySQL password for user $User" -AsSecureString
    $Password = ConvertTo-PlainText $securePassword
}

$env:MYSQL_PWD = $Password
try {
    $databaseExists = & mysql.exe --host=$DatabaseHost --port=$Port --user=$User --batch --skip-column-names `
        --execute="SELECT COUNT(*) FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = 'fruit_mall';" 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "MySQL login failed for $User@$DatabaseHost. Check the password and try again. mysql.exe: $databaseExists"
    }
    if (($databaseExists | Select-Object -Last 1).ToString().Trim() -ne "1") {
        throw "MySQL login succeeded, but database fruit_mall does not exist. Run .\scripts\init-database.ps1 first."
    }

    New-Item -ItemType Directory -Path $configDirectory -Force | Out-Null
    $jdbcUrl = "jdbc:mysql://${DatabaseHost}:${Port}/fruit_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
    $content = @(
        "# Generated by scripts/configure-local.ps1. This file is ignored by Git.",
        "spring.datasource.url=$(ConvertTo-PropertyValue $jdbcUrl)",
        "spring.datasource.username=$(ConvertTo-PropertyValue $User)",
        "spring.datasource.password=$(ConvertTo-PropertyValue $Password)"
    )
    [IO.File]::WriteAllLines($configFile, $content, [Text.UTF8Encoding]::new($false))
    Write-Host "Local database configuration saved. Restart the backend in IDEA." -ForegroundColor Green
    Write-Host "Configuration file: $configFile" -ForegroundColor DarkGray
} finally {
    Remove-Item Env:MYSQL_PWD -ErrorAction SilentlyContinue
    $Password = $null
}
